
JobsRunsBridgesTransactionsKeysConfiguration
Direct request job spec detail
shamba-fire-data-filecoin-latest
47
Created 13 minutes ago (2022-04-11 4:42:04 AM)
OverviewDefinitionErrorsRuns1
Definition
type = "directrequest"
schemaVersion = 1
name = "shamba-fire-data-filecoin-latest"
contractAddress = "0xf4434feDd55D3d6573627F39fA39867b23f4Bf7F"
maxTaskDuration = "0s"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    fetch        [type="bridge" name="shamba-common-external-adapter-bridge" requestData="{\\"id\\": $(jobSpec.externalJobID), \\"tx_hash\\": $(jobRun.logTxHash), \\"contract_address\\": $(decode_log.callbackAddr), \\"operator_address\\": $(jobRun.logAddress), \\"data\\":$(decode_cbor.data)}"]
    parse        [type="jsonparse" path="result" data="$(fetch)"]
    encode_data  [type="ethabiencode" abi="(bytes32 requestId, uint256[] result, string calldata cid)" data="{ \\"requestId\\": $(decode_log.requestId), \\"result\\": $(parse.result), \\"cid\\": $(parse.cid) }"]
    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type="ethtx" to="0xf4434feDd55D3d6573627F39fA39867b23f4Bf7F" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> encode_data -> encode_tx -> submit_tx
"""
externalJobID = "fd78aec2-3f7d-4995-bf07-99cdd38e7e6f"